### ISSUE TITLE
Combine statement seems to have no effect

### ISSUE THREAD

**Issue by alextreppass** [dbashford/mimosa-combine#1]
We've tried placing a combine statement, as per the mimosa-combine docs, into an existing mimosa project, which uses SASS.

Putting it at the top before the 'watch' definition breaks things, and putting at the bottom of the file after the 'server' definition seems to do nothing -- it compiles our SASS but no css files are combined, and there are no mimosa logs to do with css or sass or combine.

Where should the config go? Are we forgetting to add something other than a config change to our existing project?

We've tried mimosa watch --server, and mimosa build --optimize.

Latest version (0.5.5beta) of mimosa, and 0.1.0 of mimosa-combine.

Thanks

**Comment by dbashford** [comment]
Here's the AngularFunMimosa config with the combine added to it.

```
exports.config =
  combine:[
    {
      folder:"stylesheets/vendor"
      output:"stylesheets/vendor.css"
    }
  ]
  modules:['lint','require','server','minify','live-reload','web-package','combine']
  minify:
    exclude:["\\.min\\.", "main.js"]

```

It's a JSON object so where it goes isn't important, as long as it is a top level property within the object.  But because it is coffee, indentation **is** important.  Make sure you have 'combine' added to the list of modules.  If you do, the config above is redundant as it is the default and unnecessary.  But that default wasn't put there to be a default as much as it was put there to be an example.

**Comment by alextreppass** [comment]
That was it, we hadn't specified it in the 'modules' declaration.

We had already adapted the example.

Thanks for the quick response!
