### ISSUE TITLE
Error when dust compiler not used

### ISSUE THREAD

**Issue by hwride** [dbashford/mimosa-combine#10]
I'm working on a mimosa module which is being used to do custom compiling of dust templates. It registers for updating checking as follows:

``` javascript
register(['add', 'update', 'remove'], 'compile', updateDustTemplate, ['dust']);
```

The dust compiler which is not needed is overridden in mimosa-config.coffee as follows:

``` coffeescript
 compilers:
   extensionOverrides:       
     dust: null                
```

When a dust file is saved triggering the update mimosa workflow step I get the following error (with file paths removed):

```
...\node_modules\mimosa\node_modules\mimosa-bower\node_modules\bower\node_modules\tmp\lib\tmp.js:261
  throw err;
        ^
TypeError: Cannot read property 'length' of undefined
    at Array._checkForMerge [as 2] (...\node_modules\mimosa-combine\lib\index.js:40:27)
```

When the dust compiler isn't overridden in mimosa-config.coffee this error doesn't occur. 

Looking at mimosa-combine index.js, it seems to expect options.files to exist, but when a workflow callback is registered for a dust only extension then options.files does not exist on the callback, and a callback which registers for [add, update, delete] will get called when a dust file is saved when ordinarily it wouldn't.

**Comment by dbashford** [comment]
Going to dig around to figure out what the right solution to this is.

For whatever reason, if options.files doesn't exist, it shouldn't just break, so I'll go ahead and make the change to mimosa-combine to handle this and get a new version out.

One thing that happens when you turn the dust compiler off is that all the things the dust compiler does that are not just compiling also get turned off, like reading files.  So one thing you could do with your module is register something during `update/read` that reads in the file, presumably because you'll need the file text, and populates the files array.

I think I may also consider simply putting an empty `files` array in there to avoid this being a problem down the road.

**Comment by dbashford** [comment]
Updated and pushed what i believe to be the fix.  This only happens when you have another module adding handling for a extension that you had turned off.  Which is fine, that is absolutely how you'd do what you are doing.

Going to also make a small adjustment to mimosa core to make sure there's always a files array even if its empty.

**Comment by hwride** [comment]
Thanks for the quick response, this fixes things from my end.

**Comment by dbashford** [comment]
Just out of curiosity, might this module be something that ends up in NPM?  Would love to check it out!

**Comment by hwride** [comment]
This is something quite specific for this project so it probably won't go on to NPM.
