### ISSUE TITLE
combining templates dir wants the expected folder to exist in assets, not in the built folder

### ISSUE THREAD

**Issue by alextreppass** [dbashford/mimosa-combine#5]
This relates to https://github.com/dbashford/mimosa/issues/84#issuecomment-10608349

I set my dust template output file to templates/my-template

``` coffeescript
template:
    outputFileName: "templates/my-templates"
```

And then am trying to have mimosa-combine combine the templates folder:

``` coffeescript
 combine: [{
    folder:"javascripts/templates"
    output:"javascripts/templates.js"
    exclude:null
    order:null
    }
  ]
```

If the 'templates' folder doesn't exist within assets, mimosa moans at me:

```
Unable to start Mimosa for the following reason(s):
 * combine.folder entry [[ js/templates ]] must resolve to a real path, resolves
 to [[ D:\foo\assets\js\templates ]]
```

Mimosa creates the template dir for me in the built folder, not the assets folder.

Would a fallback to the built  (public) dir work if combine can't find what it wants in assets? Or am I asking too much here ;)

I can workaround it for now by creating a 'templates' folder in assets with an empty folder.

Thanks

**Comment by dbashford** [comment]
It can fall back to built, that would be no big deal.  In fact, it would validate against built since that is where the actual work takes place, but if you've never run the watch/build before then it would fail since nothing is over there.

Likewise, if I changed it to attempt both `public` and `assets`, if you were working without anything having yet been compiled, or after a `mimosa clean` you still wouldn't make it through validation.

I'd toyed with the idea at the outset, with all the startup config validation errors, of just writing them to the console, big and angry, but letting Mimosa start up regardless.  Crashing out in an ugly way isn't the best thing, and that is what would happen if invalid config makes its way through.  But if it crashes out, you've at least got a list of validation errors to remedy to get things back on track.

1) not validating the folders list or 2) letting you through that validation without stopping the run are really the only two options here I think.

**Comment by dbashford** [comment]
Seems this got left behind in my flurry to get the last few releases out.  Then it popped up on our project.

Will be removing the validation for the folders.
